  ____               _____________     __
 / __ \___ ___ ___  / __/_  __/ _ \___/ /_______  __ _
/ /_/ / _ \ -_) _ \/ _/  / / / ___/ _  // __/ _ \/  ' \
\____/ .__\__/_//_/_/   /_/ /_/   \_,_(_)__/\___/_/_/_/
    /_/
-------------------------------------------------------

        Welcome to OpenFTPd.com FTP Service,

        /pub
        Documents, Music, Software

        /incoming
        Upload your Files & Folders here

        welcome.msg
        Welcome Message

-------------------------------------------------------

           < mailto:thomas.schilb@live.de />
