[1;39;60m

         ...you're successfully passed through...
                          __ __            __
    .-----.--.--.-----.--|  |__.----.---.-|  |_.-----.
    |__ --|  |  |     |  _  |  |  __|  _  |   _|  -__|
    |_____|___  |__|__|_____|__|____|___._|____|_____|
    -ts---|_____|-------------------------------------

         T H E   D I G I T A L   S Y N D I C A T E

                    S I N C E   2 0 1 2

    --------------------------------------------------

     HTTPS:// SYNDICATE.LIVE

     NEWS ................... Information & Technical
     LINKS ...................... Linklist & Software
     GAMES ............................. PC & Console
     SOFTWARE .............. Most Common Applications
     TOOLS ................... Tools, Scripts & Lists
     TUTORIALS ................ Archive, Cheat Sheets

    --------------------------------------------------

     FTP:// FTP.OPENFTPD.COM

     + Up to 1000mbit
     + ANONYMOUS LOGIN: ON
     + USE ACTIVE MODE IN YOUR FTP-CLIENT
     + UPLOAD YOUR FILES & FOLDERS IN /INCOMING

    --------------------------------------------------

     BANDWIDTH .......................... 1000 Mbit/s
     OS ............................ DEBIAN 10 BUSTER
     HARDWARE ............ 4 CPU,  8GB RAM, 120GB HDD
     ADMIN .................... thomas.schilb@live.de
     HOMEPAGE .............. www.thomasschilb.network

    ----------------------------------------------tds-
     Last Update: 2020.03.30 @ 09:23am
